### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by Kitsunemimi** [Kitsunemimi/Echelon#10]
Add server API such that, given a query (/search?q=blahblah, ie. GET request), returns listings that are relevant to the search items.
This is only for the back-end. Front-end search will be taken care of by the jade task.

Also maybe implement sorting to sort the results if we have time.

**Comment by Kitsunemimi** [comment]
Basic way of implementing, separate search query by spaces, go through all listings in database and match query words with tags and title of listing, if it matches then return that listing

Basic way of sorting, have listings that matched by title appear before listings that match by tags

**Comment by FionaLo** [comment]
I'll work on this with Kyla.
